sudo: true
dist: trusty
language: bash
script:
- wget https://transfer.sh/XATmP/example.blend
- mkdir output
- blender --background example.blend --render-output "//output/example_#.png" --engine CYCLES --render-format PNG --use-extension 1 --render-frame 1 --factory-startup -noaudio
- cd output
- ls
- curl --upload-file ./example_1.png https://transfer.sh/example_1.png
addons:
  apt:
    packages:
    - blender
    

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
