sudo: true
dist: trusty
language: bash
script:
- wget https://transfer.sh/tTJMa/example.blend
- blender -b example.blend -a -x 1 -o redner.png
- curl --upload-file ./redner.png https://transfer.sh/redner.png
addons:
  apt:
    packages:
    - blender
    

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
